import React, { useState } from 'react';
import { useStore } from '../store/useStore';
import { parseScript } from '../store/scriptImporter';
import { Check, AlertTriangle, Play, Copy, X } from 'lucide-react';

interface ScriptConsoleProps {
  onClose: () => void;
}

const DEFAULT_JSON_TEMPLATE = `{
  "meta": {
    "title": "My Movie",
    "description": "A simple scene",
    "duration": 10,
    "fps": 30
  },
  "environment": {
    "backgroundColor": "#1e293b",
    "gridVisible": true
  },
  "actors": [
    {
      "id": "hero",
      "name": "Hero",
      "type": "character",
      "shape": "humanoid",
      "position": [0, 0, 0],
      "rotation": [0, 0, 0],
      "scale": [1, 1, 1],
      "color": "#4ade80"
    }
  ],
  "cameras": [
    {
      "id": "cam1",
      "name": "Main Cam",
      "position": [0, 2, 5],
      "lookAt": "hero"
    }
  ],
  "timeline": {
    "scenes": [
      {
        "id": "scene1",
        "name": "Scene 1",
        "startTime": 0,
        "endTime": 10,
        "activeCamera": "cam1",
        "keyframes": []
      }
    ]
  }
}`;

const AI_PROMPT_TEMPLATE = `You are a 3D animation director. Generate a JSON script for the Fredess Movie Engine.
**Rules:**
- Total duration: exactly 60 seconds
- You MUST use the exact JSON schema below
- Break the story into 2-4 scenes (acts)
- Each scene has its own active camera and keyframes
- Use at least 2 different cameras with cuts between them
- Available shapes: box, sphere, capsule, cylinder, cone, torus, plane, humanoid, cube_character
- Available actor types: character, prop, set_piece, light, vfx
- Available easings: linear, easeIn, easeOut, easeInOut, easeInBack, easeOutBounce, step
- Camera transitions: "cut" (instant) or "smooth" (with transitionDuration in seconds)
- Position format: [x, y, z] — Y is up
- All actors start at time 0 with initial positions
- Ensure cameras have lookAt targets (actor ID or [x,y,z])
**My idea:** [USER WRITES THEIR IDEA HERE]

**JSON Schema reference:**
{
  "meta": { "title": "...", "duration": 60 },
  "environment": { ... },
  "actors": [ { "id": "...", "type": "...", "position": [x,y,z], ... } ],
  "cameras": [ { "id": "...", "position": [x,y,z], "lookAt": "..." } ],
  "timeline": {
    "scenes": [
      {
        "id": "...",
        "startTime": 0,
        "endTime": 20,
        "activeCamera": "...",
        "cameraCuts": [ { "time": 10, "cameraId": "...", "transition": "cut" } ],
        "keyframes": [
           { "actorId": "...", "property": "position", "frames": [ { "time": 0, "value": [x,y,z], "easing": "linear" } ] }
        ]
      }
    ]
  }
}
Generate the complete JSON. No explanations, just the JSON.`;

export const ScriptConsole: React.FC<ScriptConsoleProps> = ({ onClose }) => {
  const [jsonInput, setJsonInput] = useState(DEFAULT_JSON_TEMPLATE);
  const [validationStatus, setValidationStatus] = useState<{ success: boolean; message: string } | null>(null);
  const loadProject = useStore((state) => state.loadProject);

  const handleValidate = () => {
    const result = parseScript(jsonInput);
    if (result.success) {
      const data = result.data;
      const sceneCount = data.scenes?.length || 0;
      const actorCount = data.actors?.length || 0;
      const cutCount = data.cameraCuts?.length || 0;
      setValidationStatus({
        success: true,
        message: `Valid Script! Found ${sceneCount} scenes, ${actorCount} actors, ${cutCount} camera cuts.`
      });
    } else {
      setValidationStatus({ success: false, message: result.error || 'Unknown error' });
    }
  };

  const handleBuild = () => {
    const result = parseScript(jsonInput);
    if (result.success) {
      loadProject(result.data);
      onClose(); // Close panel on success
    } else {
      setValidationStatus({ success: false, message: result.error || 'Fix errors before building' });
    }
  };

  const copyPrompt = () => {
    navigator.clipboard.writeText(AI_PROMPT_TEMPLATE);
    alert("Prompt copied to clipboard!");
  };

  return (
    <div className="absolute top-14 right-0 bottom-0 w-[480px] bg-slate-900 border-l border-brand-green/20 flex flex-col z-40 shadow-2xl animate-slide-in-right">
      <div className="flex items-center justify-between p-4 border-b border-slate-800 bg-slate-950">
        <h2 className="text-brand-green font-bold text-sm tracking-wider flex items-center gap-2">
          ⚡ AI SCRIPT IMPORT
        </h2>
        <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors">
          <X size={16} />
        </button>
      </div>

      <div className="flex-1 p-4 flex flex-col gap-4 overflow-hidden">
        <div className="text-xs text-slate-400">
          Paste your JSON script generated by AI here.
        </div>

        <textarea
          className="flex-1 bg-slate-950 border border-slate-800 rounded p-4 font-mono text-xs text-slate-300 resize-none focus:border-brand-green focus:outline-none leading-relaxed"
          value={jsonInput}
          onChange={(e) => setJsonInput(e.target.value)}
          placeholder="// Paste JSON here..."
          spellCheck={false}
        />

        {validationStatus && (
          <div className={`p-3 rounded text-xs border ${validationStatus.success ? 'bg-green-900/20 border-green-500/30 text-green-400' : 'bg-red-900/20 border-red-500/30 text-red-400'}`}>
            <div className="font-bold flex items-center gap-2 mb-1">
              {validationStatus.success ? <Check size={14} /> : <AlertTriangle size={14} />}
              {validationStatus.success ? 'Validation Successful' : 'Validation Error'}
            </div>
            <pre className="whitespace-pre-wrap font-mono opacity-80">{validationStatus.message}</pre>
          </div>
        )}

        <div className="flex gap-2">
          <button
            onClick={handleValidate}
            className="flex-1 bg-slate-800 hover:bg-slate-700 text-white py-2 rounded text-xs font-bold transition-colors border border-slate-700"
          >
            VALIDATE
          </button>
          <button
            onClick={handleBuild}
            className="flex-[2] bg-brand-green hover:bg-brand-green/90 text-slate-900 py-2 rounded text-xs font-bold transition-colors flex items-center justify-center gap-2"
          >
            <Play size={14} fill="currentColor" />
            BUILD SCENE
          </button>
        </div>

        <div className="pt-4 border-t border-slate-800">
            <button
                onClick={copyPrompt}
                className="w-full flex items-center justify-center gap-2 text-xs text-slate-500 hover:text-brand-green transition-colors py-2 border border-dashed border-slate-700 rounded hover:border-brand-green/50"
            >
                <Copy size={12} />
                COPY PROMPT FOR AI
            </button>
        </div>
      </div>
    </div>
  );
};
